#!/usr/bin/env python3

from sys import (
    argv as sys_argv,
    exit as sys_exit,
    stdout as sys_stdout,
    stderr as sys_stderr
)
from os import getenv
from pathlib import Path
from subprocess import check_call
import click


@click.command("verify")
@click.pass_context
@click.option(
    "-p",
    "--project-dir",
    type=str,
    metavar="path",
    help="Set the target directory for the project.",
)
@click.option(
    "-b",
    "--board",
    type=str,
    metavar="board",
    help="Set the board."
)
@click.option(
    "-v",
    "--verbose",
    is_flag=True,
    help="Show the entire output of the command.",
)
def VerifyCommand(ctx, board, project_dir, verbose):
    """
    Verify verilog sources through Icarus Verilog.
    """

    device = 'ice40' if board in ['TinyFPGA-B2'] else 'ecp5'

    IVER_PATH = 'apath'
    TARGET_SIM = 'atarget'
    YOSYS_PATH = 'path'

    sources = " ".join([item.name for item in Path(project_dir).glob("*.v")])

    opts = '-D NO_ICE40_DEFAULT_ASSIGNMENTS' if device == 'ice40' else '-D NO_INCLUDES'

    #cmd = f'iverilog {IVER_PATH} -o $TARGET -D VCD_OUTPUT={TARGET_SIM} {opts} {YOSYS_PATH}/{device}/cells_sim.v {sources}'
    cmd = f'iverilog {opts} {sources}'

    print(cmd)
    check_call(cmd, cwd=project_dir)

    print("verbose:", verbose)

    ctx.exit(0)


@click.command("build")
@click.pass_context
@click.option(
    "-b",
    "--board",
    type=str,
    metavar="board",
    help="Set the board."
)
@click.option(
    "--device",
    type=str,
    metavar="device",
    help="Set the FPGA device."
)
@click.option(
    "--package",
    type=str,
    metavar="package",
    help="Set the FPGA package."
)
@click.option(
    "-p",
    "--project-dir",
    type=str,
    metavar="path",
    help="Set the target directory for the project.",
)
@click.option(
    "-v",
    "--verbose",
    is_flag=True,
    help="Show the entire output of the command.",
)
@click.option(
    "--verbose-yosys",
    is_flag=True,
    help="Show the yosys output of the command.",
)
@click.option(
    "--verbose-pnr",
    is_flag=True,
    help="Show the pnr output of the command."
)
def BuildCommand(
    ctx,
    board,
    device,
    package,
    project_dir,
    verbose,
    verbose_yosys,
    verbose_pnr,
):
    """
    Generate bitstream through Yosys and Nextpnr.
    """

    sources = " ".join([item.name for item in Path(project_dir).glob("*.v")])
    opts = '' if verbose or verbose_yosys else '-q'
    cmd = f'yosys -p "proc; synth_ice40 -top main -json synth.json" {opts} {sources}'

    print(cmd)
    check_call(cmd, cwd=project_dir)
    sys_stdout.flush()
    sys_stderr.flush()

    boards = {
        'icezum': {
            'device': 'ICE40-HX1K',
            'package': 'TQ144'
        }
    }

    device = boards[board]['device'].split('-')[1].lower() if device is None else device
    package = boards[board]['package'].lower() if package is None else package

    pcf = [item.name for item in Path(project_dir).glob("*.pcf")][0]
    opts = '' if verbose or verbose_pnr else '-q'
    cmd = f'nextpnr-ice40 --{device} --package {package} --pcf {pcf} --json synth.json --asc pnr.asc {opts}'

    print(cmd)
    check_call(cmd, cwd=project_dir)
    sys_stdout.flush()
    sys_stderr.flush()

    cmd = 'icepack pnr.asc design.bin'

    print(cmd)
    check_call(cmd, cwd=project_dir)
    sys_stdout.flush()
    sys_stderr.flush()

    print('board:', board)

    ctx.exit(0)


@click.command("upload")
@click.pass_context
@click.option(
    "-b",
    "--board",
    type=str,
    metavar="board",
    help="Set the board."
)
@click.option(
    "--serial-port",
    type=str,
    metavar="serial-port",
    help="Set the serial port.",
)
@click.option(
    "--ftdi-id",
    type=str,
    metavar="ftdi-id",
    help="Set the FTDI id."
)
@click.option(
    "-s",
    "--sram",
    is_flag=True,
    help="Perform SRAM programming."
)
@click.option(
    "-f",
    "--flash",
    is_flag=True,
    help="Perform FLASH programming."
)
@click.option(
    "-p",
    "--project-dir",
    type=str,
    metavar="path",
    help="Set the target directory for the project.",
)
@click.option(
    "-v",
    "--verbose",
    is_flag=True,
    help="Show the entire output of the command.",
)
@click.option(
    "--verbose-yosys",
    is_flag=True,
    help="Show the yosys output of the command.",
)
@click.option(
    "--verbose-pnr",
    is_flag=True,
    help="Show the pnr output of the command."
)
def UploadCommand(
    ctx,
    board,
    serial_port,
    ftdi_id,
    sram,
    flash,
    project_dir,
    verbose,
    verbose_yosys,
    verbose_pnr,
):
    """
    Upload bitstream to the board through openFPGALoader.
    """

    print("board:", board)
    print("serial_port:", serial_port)
    print("ftdi_id:", ftdi_id)
    print("sram:", sram)
    print("flash:", flash)
    print("verbose:", verbose)
    print("verbose_yosys:", verbose_yosys)
    print("verbose_pnr:", verbose_pnr)

    ctx.exit(0)


@click.group()
def cli():
    pass

cli.add_command(VerifyCommand)
cli.add_command(BuildCommand)
cli.add_command(UploadCommand)


if __name__ == '__main__':
    toolenv = getenv('ICETOOL_CMD', 'ICETool')
    if toolenv != 'ICETool':
        check_call([toolenv] + sys_argv[1:])
        sys_exit()
    cli()
